name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Build the Docker image
      uses: actions/checkout@v2
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
